---
version: '2'

services:

  # letsencrypt-generic uses a user-defined hook to update DNS entries.
  # You need to supply your own hook, available at /dns/hook. See the
  # letsencrypt.sh repo for details about hook arguments.
  letsencrypt-generic:
    image: csmith/letsencrypt-generic:latest
    container_name: autoproxy_letsencrypt-generic
    restart: always
    volumes:
      - letsencrypt-data:/letsencrypt
      - /my/hook/script:/dns/hook
    environment:
      # For testing purposes, use the Let's Encrypt staging server.
      # Remove this for production use!
      - STAGING=yes
      # To accept Let's Encrypt's temrs of service automatically:
      #- ACCEPT_CA_TERMS=yes
      # The e-mail address to provide to Let's Encrypt.
      - EMAIL=your@email.addr
      # Any environment variables your hook needs
      - MY_SECRET=1234567890123456789012345678901234567890
